spring:
  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:mysql://localhost:3306/trafficboss?characterEncoding=utf8
    username: root
    password: dudwnsl1993!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.myproject.mapper
  mapper-locations: mapper/**/*.xml